name: flutterethicoin
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^8.1.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true